---
version: 2.1
jobs:
  build-and-scan-image:
    docker: 
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run:
          name: Start Docker Image
          command: docker run ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
      - run:
          name: Start Container Vulnerability Tooling Images
          command: | 
            docker run -d --name db arminc/clair-db:latest
            docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:latest
      - run:
          name: Download Clair Scanning Utility
          command: | 
            wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
            mv clair-scanner_linux_amd64 clair-scanner
            chmod +x clair-scanner
      - run:
          name: Ensure Vulnerability Whitelist File Exists
          command: touch clair-whitelist.yml
      - run:
          name: Scan Docker Image for Vulnerabilities
          command: | 
            while( ! wget -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 10 && docker ps ; done
            retries=0
            echo "Waiting for clair daemon to start"
            while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
            ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} || true
  release-image:
    docker: 
      - image: circleci/buildpack-deps:stable
    steps:
      - setup_remote_docker
      - run:
          name: Release Approved Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u deanshanahan --password-stdin
            docker tag ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} deanshanahan/${CIRCLE_PROJECT_REPONAME}:latest
            docker push deanshanahan/${CIRCLE_PROJECT_REPONAME}:latest 
workflows:
  version: 2
  build-master:
    jobs:
      - build-and-scan-image:
          filters:
            branches:
              only: master
      - release-image:
          requires:
            - build-and-scan-image
          filters:
            branches:
              only: master
